/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author USER
 */
public class cmboBox extends javax.swing.JFrame {

    /**
     * Creates new form cmboBox
     */
    public cmboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmboBOX = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmboBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DATA" }));
        cmboBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboBOXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(cmboBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(cmboBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmboBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboBOXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Connection c = null;
        Connection c1 = null;
        Connection c2= null;
 
        try {
        String dbURL1 = "jdbc:postgresql:Table?user=postgres=rabiarose";
            c = DriverManager.getConnection(dbURL1);
            if (c != null) {
                System.out.println("Connected to database #1");
            }
            } catch (Exception ex) {
        } finally {
            try {
                if (c != null && !c.isClosed()) {
                    c.close();
                }
                if (c1!= null && !c1.isClosed()) {
                    c1.close();
                }
                if (c2 != null && !c2.isClosed()) {
                    c2.close();
                }
            } catch (SQLException ex) {
            }
        }
        java.awt.EventQueue.invokeLater(() -> {
            new cmboBox().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmboBOX;
    // End of variables declaration//GEN-END:variables
}
